apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-shop

resources:
  - ../../base

images:
  - name: java-shop
    newName: europe-central2-docker.pkg.dev/gcp-java-gke-ci-cd/java-shop-prod/java-shop
    newTag: prod-v1

patches:
  - path: patch-deployment.yaml