apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: java-shop-backend-config
  namespace: java-shop
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /actuator/health
    port: 8080