apiVersion: v1
kind: Secret
metadata:
  name: java-shop-db-secret
  namespace: java-shop
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://POSTGRES_HOST:5432/java_shop"
  SPRING_DATASOURCE_USERNAME: "java_shop_user"
  SPRING_DATASOURCE_PASSWORD: "java_shop_password"