apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - configmap.yaml
  - backend-config.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml