apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-shop-app-sa
  namespace: java-shop
  annotations:
    iam.gke.io/gcp-service-account: java-shop-cloudsql@gcp-java-gke-ci-cd.iam.gserviceaccount.com