apiVersion: v1
kind: Service
metadata:
  name: java-shop-service
  namespace: java-shop
  annotations:
    cloud.google.com/backend-config: '{"default": "java-shop-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: java-shop-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP