apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-shop-app
  namespace: java-shop
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: java-shop-app
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"

        - name: cloud-sql-proxy
          args:
            - "--structured-logs"
            - "--port=5432"
            - "gcp-java-gke-ci-cd:europe-central2:java-shop-dev-db"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"