# PostgreSQL database - local Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/java_shop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=java_shop_user
spring.datasource.password=java_shop_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# H2 console disabled
spring.h2.console.enabled=false